### ISSUE TITLE
Error with "Browse backups" on first run

### ISSUE THREAD

**Issue by blueyed** [emersion/bups#11]
I'm looking at bups, and founds that there's an error when clicking the "Browse backups" button:

    Could not mount filesystem

    Traceback (most recent call last):
      File "…/bups/bin/../bups/gtk.py", line 875, in do_mount
        manager.mount(callbacks)
      File "…/bups/bin/../bups/manager.py", line 128, in mount
        'onerror': lambda msg, ctx: callbacks["onerror"](msg)
      File "…/bups/bin/../bups/manager.py", line 197, in mount_parents
        self.bup.set_dir(last_mount_path)
      File "…/bups/bin/../bups/worker.py", line 42, in set_dir
        os.environ['BUP_DIR'] = bup_dir
      File "…/pyenv/2.7.9/lib/python2.7/os.py", line 473, in __setitem__
        putenv(key, item)
    TypeError: must be string, not None

That's because there are no mounts / backups configured with it.

(I was looking for some functionality to browse my existing backup repo/branches, but it seems like bups will not fit my needs. I am using bup-fuse manually for this currently.)

**Comment by emersion** [comment]
Thanks for reporting the bug, I'll fix it ASAP!

**Comment by emersion** [comment]
Fixed!
